#!/bin/bash
# AI Inference GPU Frequency Deployment Script
# Generated by Production Optimization Framework

set -e

usage() {
    echo "Usage: $0 <config> [action]"
    echo "Configs: A100+LLAMA, A100+STABLEDIFFUSION, V100+STABLEDIFFUSION, etc."
    echo "Actions: deploy (default), reset, status"
    echo ""
    echo "Examples:"
    echo "  $0 A100+LLAMA deploy"
    echo "  $0 V100+STABLEDIFFUSION reset"
    echo "  $0 A100+VIT status"
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

CONFIG=$1
ACTION=${2:-deploy}

case "$CONFIG" in
    "A100+LLAMA")
        DEPLOY_CMD="nvidia-smi -ac 1215,1200"
        RESET_CMD="nvidia-smi -ac 1215,1410"
        OPTIMAL_FREQ=1200
        BASELINE_FREQ=1410
        ;;
    "A100+STABLEDIFFUSION")
        DEPLOY_CMD="nvidia-smi -ac 1215,1245"
        RESET_CMD="nvidia-smi -ac 1215,1410"
        OPTIMAL_FREQ=1245
        BASELINE_FREQ=1410
        ;;
    "V100+STABLEDIFFUSION")
        DEPLOY_CMD="nvidia-smi -ac 877,1110"
        RESET_CMD="nvidia-smi -ac 877,1380"
        OPTIMAL_FREQ=1110
        BASELINE_FREQ=1380
        ;;
    "A100+VIT")
        DEPLOY_CMD="nvidia-smi -ac 1215,1215"
        RESET_CMD="nvidia-smi -ac 1410,1410"
        OPTIMAL_FREQ=1215
        BASELINE_FREQ=1410
        ;;
    "A100+WHISPER")
        DEPLOY_CMD="nvidia-smi -ac 1215,1290"
        RESET_CMD="nvidia-smi -ac 1215,1410"
        OPTIMAL_FREQ=1290
        BASELINE_FREQ=1410
        ;;
    "V100+LLAMA")
        DEPLOY_CMD="nvidia-smi -ac 877,1365"
        RESET_CMD="nvidia-smi -ac 877,1380"
        OPTIMAL_FREQ=1365
        BASELINE_FREQ=1380
        ;;
    "V100+VIT")
        DEPLOY_CMD="nvidia-smi -ac 877,1140"
        RESET_CMD="nvidia-smi -ac 877,1380"
        OPTIMAL_FREQ=1140
        BASELINE_FREQ=1380
        ;;
    "V100+WHISPER")
        DEPLOY_CMD="nvidia-smi -ac 877,1230"
        RESET_CMD="nvidia-smi -ac 877,1380"
        OPTIMAL_FREQ=1230
        BASELINE_FREQ=1380
        ;;
    *)
        echo "❌ Unknown configuration: $CONFIG"
        echo "Available configurations:"
        echo "   A100+LLAMA"
        echo "   A100+STABLEDIFFUSION"
        echo "   V100+STABLEDIFFUSION"
        echo "   A100+VIT"
        echo "   A100+WHISPER"
        echo "   V100+LLAMA"
        echo "   V100+VIT"
        echo "   V100+WHISPER"
        exit 1
        ;;
esac

case "$ACTION" in
    "deploy")
        echo "🚀 Deploying optimal frequency for $CONFIG"
        echo "Command: $DEPLOY_CMD"
        if eval "$DEPLOY_CMD"; then
            echo "✅ Frequency deployed successfully"
            echo "Current: $(nvidia-smi --query-gpu=clocks.gr --format=csv,noheader,nounits) MHz"
        else
            echo "❌ Failed to deploy frequency"
            exit 1
        fi
        ;;
    "reset")
        echo "🔄 Resetting to baseline frequency for $CONFIG"
        echo "Command: $RESET_CMD"
        if eval "$RESET_CMD"; then
            echo "✅ Frequency reset successfully"
            echo "Current: $(nvidia-smi --query-gpu=clocks.gr --format=csv,noheader,nounits) MHz"
        else
            echo "❌ Failed to reset frequency"
            exit 1
        fi
        ;;
    "status")
        echo "📊 Status for $CONFIG:"
        echo "Optimal: ${OPTIMAL_FREQ} MHz"
        echo "Baseline: ${BASELINE_FREQ} MHz"
        echo "Current: $(nvidia-smi --query-gpu=clocks.gr --format=csv,noheader,nounits) MHz"
        echo "Temperature: $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)°C"
        echo "Power: $(nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits)W"
        ;;
    *)
        echo "❌ Unknown action: $ACTION"
        usage
        ;;
esac
