name: Feature Request
description: Suggest a new feature for the AI Inference Energy framework
title: "[FEATURE] "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - GPU Support (new GPU types)
        - Power Modeling (algorithms, metrics)
        - Profiling Tools (DCGMI, nvidia-smi)
        - Sample Collection (scripts, automation)
        - EDP Optimization (energy-delay product analysis)
        - Optimal Frequency Selection (algorithms, criteria)
        - Analysis Tools (data processing, visualization)
        - Deployment Interface (production integration)
        - Documentation
        - Testing/CI
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case or problem this feature would solve
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas for how this could be implemented, please describe them
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my work
        - Critical - Blocking my work
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with implementation
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide requirements/specifications
