# EDP Analysis Framework Configuration
# This file contains default configuration parameters for the AI Inference Energy framework

# Data Processing Configuration
data:
  # Exclude cold start effects by using run 2+ data
  exclude_cold_start: true
  default_run: 2
  validation_threshold: 0.05
  
  # Data file paths (relative to edp_analysis directory)
  data_directory: "../sample-collection-scripts"
  aggregated_data: "data_aggregation/complete_aggregation_run2.csv"
  
  # Data validation parameters
  min_data_points: 5
  max_cv_threshold: 0.3  # Coefficient of variation threshold

# Optimization Parameters
optimization:
  # Performance constraints per workload (max allowable penalty)
  performance_constraints:
    llama: 0.05           # 5% max penalty for interactive LLM
    stable_diffusion: 0.20 # 20% max penalty for image generation
    vit: 0.20             # 20% max penalty for vision tasks
    whisper: 0.15         # 15% max penalty for speech recognition
    lstm: 0.10            # 10% max penalty for lightweight models
  
  # Multi-objective optimization weights
  energy_weight: 0.7      # Weight for energy savings
  performance_weight: 0.3 # Weight for performance retention
  
  # EDP calculation parameters
  edp_methods: ["edp", "ed2p"]  # Energy-Delay Product variants
  normalize_metrics: true       # Normalize metrics before optimization

# GPU Specifications and Frequency Ranges
gpus:
  a100:
    max_frequency: 1410
    memory_frequency: 1215
    practical_range: [70, 100]  # % of max frequency for practical deployment
    frequencies: [510, 555, 600, 645, 690, 735, 780, 825, 870, 915, 960, 1005, 1050, 1095, 1140, 1185, 1230, 1275, 1320, 1365, 1410]
  
  v100:
    max_frequency: 1380
    memory_frequency: 877
    practical_range: [70, 100]
    frequencies: [510, 540, 570, 600, 630, 660, 690, 720, 750, 780, 810, 840, 870, 900, 930, 960, 990, 1020, 1050, 1080, 1110, 1140, 1170, 1200, 1230, 1260, 1290, 1320, 1350, 1380]
  
  h100:
    max_frequency: 1785
    memory_frequency: 1593
    practical_range: [70, 100]
    frequencies: [510, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1785]

# Visualization Configuration  
plotting:
  style: "seaborn-v0_8"
  figure_size: [12, 8]
  dpi: 300
  save_format: "png"
  color_palette: "Set2"
  
  # Plot types to generate
  default_plots:
    - "frequency_vs_energy"
    - "frequency_vs_performance" 
    - "edp_optimization"
    - "pareto_frontier"
    - "deployment_summary"

# Production Deployment Configuration
deployment:
  validation_timeout: 30          # Seconds to wait for frequency change validation
  rollback_on_failure: true       # Automatically rollback on deployment failure
  monitoring_interval: 5          # Seconds between monitoring checks
  
  # Deployment categories based on performance penalty
  categories:
    production_ready: 0.20         # ≤20% penalty - ready for production
    a_b_testing: 0.50             # 20-50% penalty - requires A/B testing
    batch_only: 1.0               # >50% penalty - batch processing only
  
  # Safety constraints
  min_frequency_percent: 50       # Minimum frequency as % of max (safety limit)
  max_temperature_celsius: 85     # Maximum GPU temperature during deployment

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "edp_analysis.log"
  
# Analysis Workflow Configuration
workflows:
  # Quick analysis default parameters
  quick_analysis:
    generate_plots: true
    save_results: true
    output_directory: "results"
  
  # Production optimization workflow
  production_optimization:
    include_deployment_configs: true
    generate_monitoring_scripts: true
    create_rollback_plan: true
    
  # Comparative analysis
  comparative_analysis:
    baseline_run: 1
    comparison_runs: [2, 3]
    statistical_tests: ["t_test", "mann_whitney"]

# Feature Engineering Configuration
feature_engineering:
  # FGCS-inspired features
  fgcs_features:
    - "fp_activity"
    - "dram_activity" 
    - "clock_frequency"
    - "memory_utilization"
  
  # Feature selection parameters
  max_features: 8
  selection_methods: ["correlation", "mutual_info", "rfe"]
  correlation_threshold: 0.95

# Model Validation Configuration
validation:
  cross_validation_folds: 5
  test_size: 0.2
  random_state: 42
  
  # Metrics to track
  metrics:
    - "r2_score"
    - "mean_absolute_error"
    - "mean_squared_error"
    - "energy_prediction_accuracy"
