name: llama-v100
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  # Python
  - python=3.9
  
  # PyTorch with CUDA 11.7 for V100 (compatible)
  - pytorch>=1.13.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  
  # CUDA toolkit
  - cuda-toolkit=11.7
  - cuda-runtime=11.7
  
  # Core ML/AI packages
  - numpy>=1.21.0
  - scipy
  - scikit-learn
  - pandas
  
  # Hugging Face ecosystem (older versions for stability)
  - transformers>=4.25.0
  - tokenizers>=0.13.0
  - datasets
  - accelerate>=0.16.0
  - huggingface_hub
  
  # Development and monitoring
  - ipython
  - jupyter
  - matplotlib
  - seaborn
  - tqdm
  - psutil
  - gpustat
  
  # Additional utilities
  - requests
  - urllib3
  - certifi
  
  - pip
  
  - pip:
    # Stable versions for V100 compatibility
    - torch>=1.13.0
    - transformers>=4.25.0
    - accelerate>=0.16.0
    - optimum>=1.8.0
    - safetensors
    
    # NVIDIA utilities
    - nvidia-ml-py
    - pynvml
    
    # Development tools
    - pytest
    - black
    - flake8
