name: Minimal CI

on:
  push:
    branches: [main, dev, develop]
  pull_request:
    branches: [main, dev, develop]


jobs:
  lint:
    name: Pre-commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always

  # Ultra-fast essential checks only
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          
      - name: Install essential tools
        run: |
          pip install --upgrade pip
          pip install black flake8 isort pytest coverage
          
      - name: Auto-fix formatting
        run: |
          black .
          isort .
          
      - name: Syntax check only
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
      - name: Install project dependencies
        run: pip install -r requirements.txt
        
      - name: Quick module test
        run: |
          python -c "from hardware.gpu_info import get_supported_gpus; print('✓ GPUs:', get_supported_gpus())"
          python -c "from config import GPUConfig; print('✓ Config loaded')"
          
      - name: Run tests
        run: |
          coverage run tests/run_tests.py
          coverage xml -o coverage.xml
          coverage html -d coverage_html
          bash tests/test_python_compatibility.sh

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage_html/
